config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  authenticated :user do
    root to: 'groups#index', as: :authenticated_root
  end

  resources :groups, only: [:new, :create, :index] do 
    resources :deals, only: [:new, :create, :index]
  end

  root to: 'splash#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_deals, foreign_key: 'deal_id', class_name: 'GroupDeal'

  validates :name, presence: true
  validates :amount, presence: true, numericality: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_deals, foreign_key: 'group_id', class_name: 'GroupDeal'

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/group_deal.rb
class GroupDeal < ApplicationRecord
  belongs_to :deal, class_name: 'Deal'
  belongs_to :group, class_name: 'Group'

  after_create :update_total_deals
  def update_total_deals
    group.increment!(:total_deals, deal.amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, foreign_key: 'author_id', class_name: 'Group'
  has_many :deals, foreign_key: 'author_id', class_name: 'Deal'

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @current_user = current_user
    @group_deals = Group.find(params[:group_id]).group_deals.order(created_at: :desc)
  end

  def new
    @group = Group.find(params[:group_id])
    @groups = current_user.groups
  end

  def create
    @deal = current_user.deals.new(name: params[:name], amount: params[:amount])

    if @deal.save
      @group_deal = GroupDeal.new(group_id: params[:groups], deal_id: @deal.id)
      @group_deal.save
      redirect_to group_deals_path(group_id: params[:groups]), notice: 'Deal has been created successfully!'
    else
      flash[:alert] = 'Something went wrong, Try again!'
      render :new
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = Group.where(author_id: current_user.id)
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to groups_path, notice: 'Category has been created!'
    else
      flash[:alert] = 'Something went wrong, Try again!'
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/group_deals_helper.rb
module GroupDealsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/deals/index.html.erb
<section class="container">

  <% @group_deals.each do |group_deal| %>
      <div class="border border-1 d-flex my-3">
        <img src="https://picsum.photos/200" width="80px">
        <h3 
          class="m-2"><%= group_deal.deal.name %> 
          <span class="d-block fs-6 fw-lighter mt-3"><%= "#{group_deal.created_at.day}/#{group_deal.created_at.month}/#{group_deal.created_at.year}" %></span>
        </h3>
        <div class="ms-auto pt-5 pe-3">
          <%= group_deal.deal.amount %> $
        </div>
      </div>
  <% end %>

  <div class="fixed-bottom mb-3 text-center">
   <%= link_to "New Deal", new_group_deal_path, class:"btn btn-success fs-3 w-75"  %>
  </div>

</section>


app/views/deals/new.html.erb
<section class="container">
  <%= form_with url: group_deals_path, method: :post do |f| %>
    <div class="field my-3">
      <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "name", :required => true %>
    </div>

    <div class="field my-3">
      <%= f.number_field :amount, autofocus: true, class: "form-control", placeholder: "amount", :required => true%>
    </div>

    <div class="field my-3">
      <%= f.select :groups, options_from_collection_for_select(@groups, 'id', 'name'), {}, { class: "form-control" }%>
    </div>

    <div class="text-center">
      <%= f.submit "Add Deal",  class: "btn btn-primary" %>
    </div>
  <% end %>
</section>

app/views/groups/index.html.erb
<section class="container">

 <% @groups.each do |group| %>
    <%= link_to group_deals_path(group), class: "text-reset text-decoration-none" do %>
      <div class="border border-1 d-flex my-3">
        <img src="<%= group.icon%>" width="80px">
        <h3 
          class="m-2"><%= group.name %> 
          <span class="d-block fs-6 fw-lighter mt-3"><%= "#{group.created_at.day}/#{group.created_at.month}/#{group.created_at.year}" %></span>
        </h3>
        <div class="ms-auto pt-5 pe-3">
          <%= group.total_deals || 0 %> $
        </div>
      </div>
    <% end %>
 <% end %>

  <div class="fixed-bottom mb-3 text-center">
   <%= link_to 'Add New Category', new_group_path, class:"btn btn-success fs-3 w-75"  %>
  </div>

</section>

app/views/groups/new.html.erb
<section class="container">

  <%= form_with model: @group do |form| %>
    <div class="my-3">
      <%= form.text_field :name, class: "form-control w-100", placeholder: "Name" %>
    </div>

    <div class="my-3">
      <%= form.text_field :icon, class: "form-control w-100", placeholder: "Icon" %>
    </div>

    <div class="text-center m-3">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>

  <% end %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <% if user_signed_in? %>
      <header>
        <%= render 'shared/navbar' %>
      </header>
    <% end %>
    
    <main>
      <%= render 'shared/flash' %>
      <%= yield %>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:success] %>
  <div class="alert alert-success mt4" role="alert">
    <%= flash[:success] %>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-info mt4" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger mt4" role="alert">
    <%= alert %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger mt4" role="alert">
    <%= alert %>
  </div>
<% end %>



app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary px-3">
  <button class="navbar-toggler ml-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if current_page?(authenticated_root_path) %>
    <h2 class="navbar-brand">CATEGORIES</h2>  
    <% elsif current_page?(new_group_path) %>
     <h2 class="navbar-brand">Add Category</h2>
    <% else %>
     <h2 class="navbar-brand">TRANSACTIONS</h2>
  <% end %>
  
  <%= image_tag "search.svg", width: '25', role: 'button'%> 
  
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto my-3 mb-lg-0">
        <li class="nav-item mb-2">
          <%= link_to 'Categories', root_path, class: 'nav-link btn ' %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link btn btn-outline-danger' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/splash/index.html.erb
<section class="d-flex flex-column align-items-center gap-3 vh-100" >

  <%= image_tag "budget-big.jpg", width: '100%', height: '80%'%> 

  <div class="text-center w-100">
    <%= link_to "LOG IN", new_user_session_path, class: 'btn btn-primary w-75 mb-1'%>
    <%= link_to "SIGN UP", new_user_registration_path, class: 'btn btn-primary w-75'%>
  </div>
</section>